---
name: List-oo
version: v0.2.1
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: object interface to list (array) methods
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=List-oo
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/List-oo/trunk
requires:
  List::MoreUtils: 0.21
  List::Util: 0
  perl: 5.8.1
build_requires:
  Module::Build: 0.26
  Test::More: 0
  Test::NoWarnings: 0
provides:
  List::oo:
    file: lib/List/oo.pm
    version: v0.2.1
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
